packages/core/src/Digm.ts, packages/core/src/features/BaseFeature.ts, packages/core/src/features/SceneCamera.ts, packages/core/src/features/SceneEdit.ts, packages/core/src/features/index.ts, packages/core/src/features/utils.ts
=> feat(core): implement sceneedit

packages/core/src/Digm.ts, packages/core/src/features/Section.ts, packages/core/src/features/index.ts
=> feat(core): implement section

packages/core/src/Digm.ts, packages/core/src/features/Covering.ts, packages/core/src/features/index.ts
=> feat(core): complete the covering  encapsulation

packages/core/src/Digm.ts, packages/core/src/events/RenderEvent.ts, packages/core/src/events/event-type.ts, packages/core/src/features/Path.ts, packages/core/src/features/index.ts
实现 Path（路径）功能，并基于 Covering（覆盖物）添加了两个 `@enhance` 方法 `removePath()` 和 `removeAllPath()`
=> feat(core): implement path

packages/core/src/Digm.ts, packages/core/src/events/event-type.ts, packages/core/src/features/Raster.ts, packages/core/src/features/index.ts
实现 Raster（栅格图）功能，并基于 Covering（覆盖物）添加了两个 `@enhance` 方法 `removeRaster()` 和 `removeAllRaster()`
=> feat(core): implement raster features and events

packages/core/src/Digm.ts, packages/core/src/events/event-type.ts, packages/core/src/features/HeatMap.ts, packages/core/src/features/index.ts
实现 HeatMap（热力图）功能，包含区域热力图、柱状热力图、点云热力图、路径热力图，并基于 Covering（覆盖物）实现了对应热力图的删除功能
=> feat(core): implement heatmap features and events

packages/core/src/Digm.ts, packages/core/src/events/event-type.ts, packages/core/src/features/MigrationMap.ts, packages/core/src/features/index.ts
=> feat(core): implement migrationmap features and events

package.json, pnpm-lock.yaml
update `@ombro/ts-config@1.4.0 -> @ombro/ts-config@1.4.2`
=> chore: update dependency

packages/vue/src/components/DigmV.vue
=> fix(vue): import type check

packages/core/src/Digm.ts, packages/core/src/features/POI.ts, packages/core/src/features/index.ts
=> feat(core): implement POI features

packages/core/src/Digm.ts, packages/core/src/events/event-type.ts, packages/core/src/features/HighlightArea.ts, packages/core/src/features/index.ts
=> feat(core): implement HighlightArea

packages/core/src/Digm.ts, packages/core/src/events/event-type.ts, packages/core/src/features/TDText.ts, packages/core/src/features/index.ts
=> feat(core): implements TDText methods and events

packages/react/.eslintrc.js, packages/react/src/hooks/digm.ts, packages/vue/src/hooks/digm.ts, playgrounds/react/src/App.tsx, playgrounds/vue/src/App.vue
- `@cphayim/digm-vue`
- `@cphayim/digm-react`
```ts
// callback executed when digm rendering is complete
useDigmReady((digm) => {
console.log('DIGM is ready')
})
```
=> feat(vue, react): add `useDigmReady` hook

packages/core/src/Digm.ts, packages/core/src/events/event-type.ts
- `@cphayim/digm-core`
Fill in the missing event types
=> fix(core): missing event types and comments

packages/core/src/events/event-type.ts
due to http://superapi.51aes.com/sample
=> fix(core): update type

package.json, pnpm-lock.yaml
Degraded vite-plugin-dts to v1.6.6
=> fix(deps): vite-plugin-dts v1.7 build failed

CHANGELOG.md, packages/core/package.json, packages/react/package.json, packages/shared/package.json, packages/vue/package.json
=> chore(release): v0.2.5

packages/core/src/features/SceneCamera.ts
- **@cphayim-digm/core**
**@cphayim-digm/core**
- Ability to save current lens type when setting lens mode, via `digm.sceneCamera.getCurrentCameraType()`
=> feat(core): save current `cameraType`

CHANGELOG.md, packages/core/package.json, packages/react/package.json, packages/shared/package.json, packages/vue/package.json
=> chore(release): v0.2.6

CHANGELOG.md, packages/core/package.json, packages/react/package.json, packages/shared/package.json, packages/vue/package.json, pnpm-lock.yaml
=> chore(release): v0.2.7
